name: Build Docker Container

on:
  push:
    branches:
      - master
    # This regex checks for version numbers in the commit message
    paths-ignore:
      - '**.md'
    # Example versioning pattern: v1.0.0
    # Adjust the regex as needed for your versioning scheme
    if: contains(github.event.head_commit.message, 'v')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: snuids/nyx_ui:${{ github.event.head_commit.message }}